# Docker Compose file Reference (https://docs.docker.com/compose/compose-file/)
version: '3'

#Define services
services:

  #PostgreSQL Database for the application
  crud-postgres:
    image: "postgres:alpine"
    container_name: crud-postgres
    #Volume mounted for database for the storage
    volumes:
      - crud-data:/var/lib/postgresql/data
    ports:
      - 5432:5432 # Forward the exposed port 5432 on the container to port 5432 on the host machine

    #Environment variable for DB name, user and password
    environment:
      - POSTGRES_DB=students
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres

  #Back-end Spring Boot Application
  crud-app:
    #The docker file in scrum-app build the jar and provides the docker image with the following name.
    build: .
    container_name: crud-app

    #Environment variables for Spring Boot Application.
    environment:
      - DB_SERVER=crud-postgres
      - POSTGRES_DB=students
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    ports:
      - 8080:8080 # Forward the exposed port 8080 on the container to port 8080 on the host machine
    links:
      - crud-postgres
    depends_on:
      - crud-postgres

#Volumes for DB data
volumes:
  crud-data:
